# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        alias: black
        name: black
        language_version: python3.11
        files: skshapes/|tests/
        verbose: true

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        alias: flake8
        name: flake8
        language_version: python3.11
        additional_dependencies: [
          flake8-docstrings,
          flake8-bugbear,
          flake8-builtins,
          flake8-comprehensions,
          flake8-annotations,
        ]
        files: skshapes/
        verbose: true

  - repo: https://github.com/scientific-python/cookie
    rev: 2023.12.21
    hooks:
      - id: sp-repo-review
