name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name : Create artifacts directory
        run: |
          mkdir -p artifacts/
      
      - name: Install package (with dependencies for linting, testing and building doc)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: syntax checking with flake8
        run: |
          flake8 skshapes

      - name: Test with pytest
        run: |
          export SKSHAPES_FLOAT_DTYPE=float32
          pytest --cov-config=.coveragerc --cov=skshapes --cov-report=html test/
          cp -r htmlcov artifacts/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          path: artifacts/